[project]
name = "ai-engineer-tienda-hogar"
version = "0.1.0"
description = "Customer support agent for tienda hogar"
readme = "README.md"
authors = [
    { name = "cristopxer", email = "cristopherortiz457@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "faiss-cpu>=1.15.1",
    "fastapi>=0.142.2",
    "langchain>=1.4.3",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.7",
    "langgraph>=1.2.12",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
ai-engineer-tienda-hogar = "ai_engineer_tienda_hogar:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "xd",
]
